/**
 * DTR C3.2 - Algerian Climate Data
 * Complete Standard 48 Wilayas database mapped to exact thermal zones.
 */

export const CLIMATE_ZONES = {
  A: { baseTemp: 4, dailyRange: 8, name: "Zone A (Littoral)" },
  B: { baseTemp: 2, dailyRange: 10, name: "Zone B (Tell)" },
  C: { baseTemp: -2, dailyRange: 12, name: "Zone C (Hauts Plateaux)" },
  D: { baseTemp: 5, dailyRange: 18, name: "Zone D (Sahara)" },
};

export const WILAYAS = [
  { id: 1, name: "Adrar", zone: "D" },
  { id: 2, name: "Chlef", zone: "A" }, 
  { id: 3, name: "Laghouat", zone: "C" },
  { id: 4, name: "Oum El Bouaghi", zone: "C" },
  { id: 5, name: "Batna", zone: "C" },
  { id: 6, name: "Béjaïa", zone: "A" },
  { id: 7, name: "Biskra", zone: "D" },
  { id: 8, name: "Béchar", zone: "D" },
  { id: 9, name: "Blida", zone: "B" },
  { id: 10, name: "Bouira", zone: "B" },
  { id: 11, name: "Tamanrasset", zone: "D" },
  { id: 12, name: "Tébessa", zone: "C" },
  { id: 13, name: "Tlemcen", zone: "A" },
  { id: 14, name: "Tiaret", zone: "C" },
  { id: 15, name: "Tizi Ouzou", zone: "A" },
  { id: 16, name: "Alger", zone: "A" },
  { id: 17, name: "Djelfa", zone: "C" },
  { id: 18, name: "Jijel", zone: "A" },
  { id: 19, name: "Sétif", zone: "C" },
  { id: 20, name: "Saïda", zone: "C" },
  { id: 21, name: "Skikda", zone: "A" },
  { id: 22, name: "Sidi Bel Abbès", zone: "B" },
  { id: 23, name: "Annaba", zone: "A" },
  { id: 24, name: "Guelma", zone: "A" },
  { id: 25, name: "Constantine", zone: "B" },
  { id: 26, name: "Médéa", zone: "C" },
  { id: 27, name: "Mostaganem", zone: "A" },
  { id: 28, name: "M'Sila", zone: "A" },
  { id: 29, name: "Mascara", zone: "A" },
  { id: 30, name: "Ouargla", zone: "D" },
  { id: 31, name: "Oran", zone: "A" },
  { id: 32, name: "El Bayadh", zone: "C" },
  { id: 33, name: "Illizi", zone: "D" },
  { id: 34, name: "Bordj Bou Arreridj", zone: "C" },
  { id: 35, name: "Boumerdès", zone: "B" },
  { id: 36, name: "El Tarf", zone: "B" },
  { id: 37, name: "Tindouf", zone: "D" },
  { id: 38, name: "Tissemsilt", zone: "C" },
  { id: 39, name: "El Oued", zone: "C" },
  { id: 40, name: "Khenchela", zone: "C" },
  { id: 41, name: "Souk Ahras", zone: "B" },
  { id: 42, name: "Tipaza", zone: "A" },
  { id: 43, name: "Mila", zone: "C" },
  { id: 44, name: "Aïn Defla", zone: "B" },
  { id: 45, name: "Naâma", zone: "C" },
  { id: 46, name: "Aïn Témouchent", zone: "B" },
  { id: 47, name: "Ghardaïa", zone: "D" },
  { id: 48, name: "Relizane", zone: "A" },
  { id: 0, name: "(Autre / Other)", zone: "A" },
];